version: '3.8'

services:
  postgres:
    image: postgres:13-alpine3.17
    container_name: PostgresDB_tests
    restart: on-failure
    ports:
      - "5433:5432"
    env_file:
      - auth_service/tests/utils/.env
    expose:
      - "5433"
    volumes:
      - postgres_tests_volume:/var/lib/postgresql/data/

  auth_service:
    container_name: FlaskAUTH_tests
    build:
      context: auth_service
    image: auth_service
    env_file:
        - auth_service/tests/utils/.env
    ports:
        - "8089:8089"

  redis:
    image: redis:7.0-alpine
    container_name: redis_tests
    command:
      - redis-server
    ports:
      - "6379:6379"

  tests:
    container_name: tests
    image: auth_service
    env_file:
        - auth_service/tests/utils/.env
    entrypoint: >
      sh -c "python3 -m pip install --upgrade pip
      && pip install --default-timeout=100 -r /auth/tests/requirements.txt
      && python3 /auth/tests/utils/wait_for_api.py
      && pytest -rfe -v  /auth/tests/tests_pers_acc.py
      && pytest -rfe -v  /auth/tests/test_roles.py
      && pytest -rfe -v  /auth/tests/test_users_roles.py"
    network_mode: "host"

volumes:
  postgres_tests_volume:
